name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 1.11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: sudo ./gradlew build
    - name: Archive lint results
      uses: actions/upload-artifact@v2.3.1
      with:
        name: lint-results
        path: /home/runner/work/android-webview/android-webview/app/build/reports/lint-results-debug.html
 
